### ISSUE TITLE
How do you trigger a "leave" transition?

### ISSUE THREAD

**Issue by matthew-dean** [jcoreio/react-router-transition-switch#2]
Given the example from the docs:
```jsx
<Switch component={Fader}>
  <Route path="/red" component={Red}/>
  <Route path="/green" component={Green} />
  <Route path="/blue" component={Blue} />
</Switch>
```
The first time the "/red" path is matched, I want to mount it and immediately fade it in. If the route then changes to "/green", then before anything happens, I want the `Red` component to play its "leave" animation (like "fade out"), and once that's done, then the `Green` component can play its "enter" animation. How would I manage those transitions with this library?

**Comment by jedwards1211** [comment]
It has to be managed by the `Fader` component (my [`react-fader`](https://github.com/jcoreio/react-fader) library does this; when its child changes from `<Red />` to `<Green />`, first it fades out `<Red />` then it mounts and fades in `<Green />`.

I guess the name of this library is a bit misleading in that it doesn't manage any transition state itself; `Switch` can be used for any case where you want to wrap the matched route in a parent component.  But I called it `react-router-transition-switch` because I usually use it for wrapping the matched route in a transition-management component like `react-fader`.
